#!/usr/bin/env node
// Sheets snapshot -> D1 import file + reconciliation report.
//
//   node scripts/sheets-to-d1.mjs [data/sheets-snapshot.json] [--out data/d1-import.sql]
//
// 1. Runs server/migrate/transform.js (strict) on the snapshot.
// 2. Writes one INSERT file in FK-safe order.
// 3. Loads migrations + that file into an in-memory SQLite and reconciles:
//    rows per sheet vs table (minus what the transform reported dropped),
//    waybill loads, SUM(Total) of Billing Lines, helper counts, and
//    PRAGMA foreign_key_check. Exits non-zero on any mismatch.
// Apply the file with `npm run db:seed:local` or
// `wrangler d1 execute <db> --remote --file data/d1-import.sql`.

import fs from 'node:fs';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { transform } from '../server/migrate/transform.js';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const args = process.argv.slice(2);
const outIdx = args.indexOf('--out');
const outFile = outIdx !== -1 ? args[outIdx + 1] : path.join(ROOT, 'data', 'd1-import.sql');
const inFile = args.find((a, i) => !a.startsWith('--') && (outIdx === -1 || i !== outIdx + 1)) || path.join(ROOT, 'data', 'sheets-snapshot.json');

const snapshot = JSON.parse(fs.readFileSync(inFile, 'utf8'));

let tables, report;
try {
  ({ tables, report } = transform(snapshot, { strict: true }));
} catch (err) {
  console.error(err.message);
  process.exit(1);
}

// ---- SQL file
const lit = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const lines = ['-- Generated by scripts/sheets-to-d1.mjs from ' + path.basename(inFile), 'PRAGMA defer_foreign_keys = on;'];
// A full load: the target starts empty, including the 0002_seed.sql defaults
// (their ids would collide with the imported rows). Children first.
Object.keys(tables).reverse().forEach((table) => lines.push(`DELETE FROM ${table};`));
lines.push('DELETE FROM sessions;');
Object.entries(tables).forEach(([table, rows]) => {
  if (!rows.length) return;
  const cols = Object.keys(rows[0]);
  const head = `INSERT INTO ${table} (${cols.join(', ')}) VALUES\n`;
  let buf = [];
  let size = 0;
  const flush = () => { if (buf.length) lines.push(head + buf.join(',\n') + ';'); buf = []; size = 0; };
  rows.forEach((r) => {
    const v = `(${cols.map((c) => lit(r[c])).join(', ')})`;
    buf.push(v);
    size += v.length;
    if (buf.length >= 100 || size > 60000) flush();   // D1 caps a statement at 100 KB
  });
  flush();
});
fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join('\n') + '\n');

// ---- Reconcile against a fresh database loaded from that file
const db = new DatabaseSync(':memory:');
for (const f of ['0001_init.sql', '0002_seed.sql']) db.exec(fs.readFileSync(path.join(ROOT, 'migrations', f), 'utf8'));
db.exec(fs.readFileSync(outFile, 'utf8'));

const count = (sql) => Number(db.prepare(sql).get().n);
const sheetRows = (name) => (snapshot[name] || []).slice(1).filter((r) => r[0] !== '' && r[0] !== null && r[0] !== undefined);
const droppedFrom = (sheet) => report.dropped.filter((d) => d.startsWith(sheet + ' ID')).length;
const col = (sheet, name) => ((snapshot[sheet] || [[]])[0] || []).map((h) => String(h).trim()).indexOf(name);

const checks = [];
const check = (label, expected, actual) => checks.push({ label, expected, actual, ok: expected === actual });

[['Users', 'users'], ['Billing Categories', 'billing_categories'], ['Route Type Map', 'route_type_map'],
  ['Customer Group Colors', 'customer_group_colors'], ['Waybill Prefixes', 'waybill_prefixes'],
  ['Employees', 'employees'], ['Trucks', 'trucks'], ['Outlets', 'outlets'], ['Trips', 'trips'],
  ['Route Frequency Log', 'route_frequency_log'], ['Fuel Prices', 'fuel_prices'],
  ['Billing Charge Types', 'billing_charge_types'], ['Billing Lines', 'billing_lines'], ['Audit Log', 'audit_log'],
].forEach(([sheet, table]) => {
  if (!snapshot[sheet]) return;
  check(`${sheet} rows -> ${table}`, sheetRows(sheet).length - droppedFrom(sheet), count(`SELECT COUNT(*) n FROM ${table}`));
});

// Waybills: one row per (number, FO) load; every sheet row's trip points at it.
{
  const wb = sheetRows('Waybills');
  const n = col('Waybills', 'Waybill Number'), fo = col('Waybills', 'FO Number'), tripCol = col('Waybills', 'Trip ID');
  const loads = new Set(wb.map((r) => `${String(r[n]).trim().toUpperCase()}|${String(r[fo]).trim()}`));
  check('Waybills loads (number+FO) -> waybills', loads.size, count('SELECT COUNT(*) n FROM waybills'));
  const tripsWithWb = new Set(wb.map((r) => Number(r[tripCol]))).size;
  check('Waybills trip links -> trips.waybill_id', tripsWithWb, count('SELECT COUNT(*) n FROM trips WHERE waybill_id IS NOT NULL'));
}

// Helpers: every ID in the CSV cells (max 3 per trip) becomes a row.
{
  const h = col('Trips', 'Helper IDs');
  const expected = sheetRows('Trips').reduce((s, r) => s + String(r[h] ?? '').split(',').map((x) => x.trim()).filter((x) => x !== '' && !Number.isNaN(Number(x))).slice(0, 3).length, 0);
  check('Trips helper IDs -> trip_helpers', expected - report.dropped.filter((d) => /helper \d+ not found/.test(d)).length, count('SELECT COUNT(*) n FROM trip_helpers'));
  const dh = col('Default Assignments', 'Default Helper IDs');
  const expectedDefault = sheetRows('Default Assignments').reduce((s, r) => s + String(r[dh] ?? '').split(',').map((x) => x.trim()).filter((x) => x !== '' && !Number.isNaN(Number(x))).slice(0, 3).length, 0);
  check('Default helper IDs -> truck_default_helpers', expectedDefault, count('SELECT COUNT(*) n FROM truck_default_helpers'));
}

// Money: the billing total survives to the cent.
if (snapshot['Billing Lines']) {
  const t = col('Billing Lines', 'Total');
  const expected = Math.round(sheetRows('Billing Lines').reduce((s, r) => s + (Number(r[t]) || 0), 0) * 100) / 100;
  check('SUM(Billing Lines.Total) -> SUM(total)', expected, Math.round(count('SELECT COALESCE(SUM(total),0) n FROM billing_lines') * 100) / 100);
}

// Freight Rates: one row per non-blank band cell.
if (snapshot['Freight Rates']) {
  const headers = snapshot['Freight Rates'][0].map((h) => String(h).trim());
  const bandCols = headers.map((h, i) => (/^\d+\.01-\d+$/.test(h) ? i : -1)).filter((i) => i !== -1);
  const droppedIds = new Set(report.dropped.map((d) => (/^Freight Rates ID (\d+):/.exec(d) || [])[1]).filter(Boolean).map(Number));
  const expected = sheetRows('Freight Rates').filter((r) => !droppedIds.has(Number(r[0]))).reduce((s, r) => s + bandCols.filter((i) => r[i] !== '' && r[i] !== null && r[i] !== undefined && !Number.isNaN(Number(r[i]))).length, 0);
  check('Freight Rates band cells -> freight_rates', expected, count('SELECT COUNT(*) n FROM freight_rates'));
}

const fkProblems = db.prepare('PRAGMA foreign_key_check').all();
check('Unresolved foreign keys', 0, fkProblems.length);

// ---- Report
console.log(`Wrote ${path.relative(ROOT, outFile)}\n`);
console.log('Reconciliation');
checks.forEach((c) => console.log(`  ${c.ok ? 'OK  ' : 'FAIL'} ${c.label}: ${c.expected} -> ${c.actual}`));
if (report.dropped.length) {
  console.log(`\nDropped / cleared by the transform (${report.dropped.length}) — fix the sheet or accept:`);
  report.dropped.forEach((d) => console.log('  - ' + d));
}
if (fkProblems.length) {
  console.log('\nForeign key problems:');
  fkProblems.slice(0, 20).forEach((p) => console.log('  ', JSON.stringify(p)));
}
const failed = checks.filter((c) => !c.ok);
if (failed.length) {
  console.error(`\n${failed.length} check(s) failed.`);
  process.exit(1);
}
console.log('\nAll checks passed.');
