#!/usr/bin/env node
// ============================================================
//  AngeLoyal OMS — sync-backlog.mjs
//  Regenerates BACKLOG.md as a COMPACT snapshot of the live
//  GitHub Project / Issues. GitHub is the source of truth;
//  BACKLOG.md is a generated, committed mirror for offline /
//  no-auth reading (and for cold Claude sessions).
//
//  Usage:
//    node scripts/sync-backlog.mjs                 # dry run: print snapshot
//    node scripts/sync-backlog.mjs --apply         # overwrite BACKLOG.md
//
//  Status source (in priority order):
//    1. A GitHub Project board, if you pass it (gives Todo / In
//       Progress / Done from the board's Status field):
//         --project <number> --owner <user-or-org>
//       or env: BACKLOG_PROJECT, BACKLOG_OWNER
//    2. Otherwise, plain issues: open -> Todo, closed -> Done.
//
//  Requires the `gh` CLI installed + authenticated (`gh auth login`).
// ============================================================

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BACKLOG_PATH = join(__dirname, '..', 'BACKLOG.md');

const args = process.argv.slice(2);
const APPLY = args.includes('--apply');
const argVal = (flag) => { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : undefined; };
const PROJECT = argVal('--project') || process.env.BACKLOG_PROJECT;
const OWNER = argVal('--owner') || process.env.BACKLOG_OWNER;

const PHASE_NAMES = {
  1: 'Phase 1 — Records, Dispatch & Waybills',
  2: 'Phase 2 — Billing & Payroll',
  3: 'Phase 3 — Visibility & Alerts',
};

function gh(argv) {
  return execFileSync('gh', argv, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

// Normalize a labels value (array of strings or of {name}) to string[].
function labelNames(labels) {
  if (!Array.isArray(labels)) return [];
  return labels.map(l => (typeof l === 'string' ? l : (l && l.name) || '')).filter(Boolean);
}

// Build a normalized item from id/title/status/labels/number/url.
function toItem({ title, status, labels, number, url }) {
  const m = String(title).match(/^\[P(\d+)-(\d+)\]\s*(.+?)\s*$/);
  if (!m) return null; // not a backlog-format issue; ignore
  const names = labelNames(labels);
  const priority = (names.find(n => /^P[012]$/.test(n))) || '';
  return {
    phase: Number(m[1]),
    id: `P${m[1]}-${m[2]}`,
    sortKey: Number(m[1]) * 1000 + Number(m[2]),
    title: m[3],
    status: status || '',
    priority,
    number,
    url,
  };
}

function fetchFromProject() {
  const out = gh(['project', 'item-list', PROJECT, '--owner', OWNER, '-L', '1000', '--format', 'json']);
  const data = JSON.parse(out);
  const items = data.items || [];
  return items.map(it => {
    const c = it.content || {};
    return toItem({
      title: it.title || c.title,
      status: it.status || '',           // board "Status" single-select field
      labels: it.labels || c.labels,
      number: c.number,
      url: c.url,
    });
  }).filter(Boolean);
}

function fetchFromIssues() {
  const out = gh(['issue', 'list', '--state', 'all', '-L', '1000',
    '--json', 'number,title,state,labels,url']);
  return JSON.parse(out).map(i => toItem({
    title: i.title,
    status: i.state === 'CLOSED' || i.state === 'closed' ? 'Done' : 'Todo',
    labels: i.labels,
    number: i.number,
    url: i.url,
  })).filter(Boolean);
}

function render(items) {
  const now = new Date().toISOString().slice(0, 10);
  const sourceNote = PROJECT
    ? `GitHub Project #${PROJECT} (@${OWNER})`
    : 'GitHub Issues (open → Todo, closed → Done)';

  const lines = [];
  lines.push('# AngeLoyal OMS — Backlog (generated snapshot)');
  lines.push('');
  lines.push(`> **Generated by \`npm run backlog:sync\` on ${now} from ${sourceNote}. Do not hand-edit.**`);
  lines.push('> Source of truth is the GitHub Project board (you + QA work there). Full description & acceptance criteria live in each issue — `gh issue view <n>`.');
  lines.push('> Bootstrap a fresh board once with `npm run backlog:seed -- --apply` (parses git history of this file). Add new items as GitHub issues titled `[P<phase>-<n>] Title` with a `P0/P1/P2` label.');
  lines.push('');

  for (const phase of [1, 2, 3]) {
    const group = items.filter(i => i.phase === phase).sort((a, b) => a.sortKey - b.sortKey);
    lines.push(`## ${PHASE_NAMES[phase]}`);
    lines.push('');
    if (!group.length) { lines.push('_No items._', ''); continue; }
    lines.push('| ID | Item | Status | Pri | Issue |');
    lines.push('| :-- | :-- | :-- | :-- | :-- |');
    for (const i of group) {
      const issue = i.number ? `[#${i.number}](${i.url})` : '';
      lines.push(`| ${i.id} | ${i.title} | ${i.status} | ${i.priority} | ${issue} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function main() {
  if ((PROJECT && !OWNER) || (!PROJECT && OWNER)) {
    console.error('Both --project and --owner (or BACKLOG_PROJECT + BACKLOG_OWNER) are required for project mode.');
    process.exit(1);
  }
  const items = PROJECT ? fetchFromProject() : fetchFromIssues();

  if (!items.length) {
    console.error('No backlog-format issues found (titles like "[P2-01] ...").\n' +
      'Run `npm run backlog:seed -- --apply` first. Not overwriting BACKLOG.md.');
    process.exit(1);
  }

  const md = render(items);
  console.log(`Synced ${items.length} items from ${PROJECT ? `Project #${PROJECT}` : 'Issues'}.`);

  if (APPLY) {
    writeFileSync(BACKLOG_PATH, md + '\n', 'utf8');
    console.log(`Wrote ${BACKLOG_PATH}. Commit it to keep the repo snapshot current.`);
  } else {
    console.log('\n--- DRY RUN (use --apply to overwrite BACKLOG.md) ---\n');
    console.log(md);
  }
}

main();
